services:
  db:
    image: postgres:15
    restart: always
    container_name: postgresql
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      #      - ./data/postgresql:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    container_name: transcendence
    command: >
      sh -c "python transcendence-api/manage.py migrate &&
             python transcendence-api/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  redis:
    image: redis:7
    restart: always
    container_name: redis
    env_file: .env
    ports:
      - "6379:6379"
