services:
  db:
    image: postgres:15
    restart: always
    container_name: postgresql
    environment:
      - POSTGRES_DB=transcendence
      - POSTGRES_USER=beautipong
      - POSTGRES_PASSWORD=beautipong123
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

