services:
  db:
    image: postgres:15
    restart: always
    container_name: postgresql
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data