# Generated by Django 4.2.15 on 2024-08-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattingroom',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
