# Generated by Django 4.2.15 on 2024-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingRoom', '0002_chattingroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattingroom',
            name='user1_is_in_chat_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chattingroom',
            name='user2_is_in_chat_room',
            field=models.BooleanField(default=False),
        ),
    ]
