# Generated by Django 4.2.15 on 2024-08-14 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_alter_friend_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
