# Generated by Django 4.2.15 on 2024-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_status',
            field=models.CharField(choices=[('read', 'Read'), ('no_read', 'No Read')], default='no_read', max_length=10),
        ),
    ]
