# Generated by Django 4.2.14 on 2024-08-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_match_cnt_customuser_win_cnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
